### ISSUE TITLE
Changing configs has no affect

### ISSUE THREAD

**Issue by D-Bigboy-302** [MostafaSabry55/Rough-Tweaks-Revamped#1]
Forge Version: 1.16.4-34.1.42
Mod Version: 2.1

Hi! Changing the values in the config seems to have no effect for me. The items still heal the default amount along with how many ticks it takes to apply a heal. I don't appear to have any mod conflicts. Even tested it with just Rough Tweaks installed, still no changes.

Thank you for porting this mod! You're amazing! Merry Christmas as well!

**Comment by SpaceXVI** [comment]
First of all, merry christmas for you! and thanks for using my mod and reporting this bug!

Will check this bug as soon as I can but for the time being I can check the bug tomorrow! Sorry for any inconveniences

**Comment by SpaceXVI** [comment]
Interesting... looks like configs don't do any changes at all, general configs seem fine but others are abit broken, will try to fix this

**Comment by SpaceXVI** [comment]
Had some free time to fix the issue, thanks to diesieben07 for helping me fixing it, will do some finishing touches then push the update!

**Comment by D-Bigboy-302** [comment]
Awesome! Thank you so much! I also hope your holidays went well!

**Comment by SpaceXVI** [comment]
Thank you for reporting this bug once again, uploaded the file and it should hopefully have the issues fixed! (Sorry for the delay, my net suddenly died). Not closing this issue till you confirm that everything is working just fine!

**Comment by D-Bigboy-302** [comment]
Howdy! I was able to test it thoroughly and everything seems to be working! I changed every value to my own liking and the game is responding to those changes. Super awesome! Thanks again for the fix :)

**Comment by SpaceXVI** [comment]
You're very welcome, have a nice day!
