### ISSUE TITLE
[1.18.2] Passive mobs drop either salve, a plaster or a bandage

### ISSUE THREAD

**Issue by DeshiDesu** [MostafaSabry55/Rough-Tweaks-Revamped#10]
Config file says only hostile mobs drop a salve, a plaster or a bandage, but they also drop for passive mobs such as cows.

>roughtweaks-1.18.2-1.1.1.jar

**Comment by SpaceXVI** [comment]
Oh that definitely shouldn't be happening. I'll finish my exams tomorrow so hopefully I'll have an update for that soon. Thanks for letting me know.

**Comment by DeshiDesu** [comment]
![2023-05-22_20 44 12](https://github.com/SpaceXVI/Rough-Tweaks-Revamped/assets/120287925/5d5e99df-2f7f-4560-8b77-004427f07197)
![2023-05-22_20 49 03](https://github.com/SpaceXVI/Rough-Tweaks-Revamped/assets/120287925/548bb16d-7f85-4b6c-85db-a9ed5c72bfd4)
![2023-05-22_20 51 14](https://github.com/SpaceXVI/Rough-Tweaks-Revamped/assets/120287925/9c398e94-aa6a-45fb-ac04-7833842a0101)
![2023-05-22_20 52 34](https://github.com/SpaceXVI/Rough-Tweaks-Revamped/assets/120287925/7965071a-695b-4c90-82d6-423db7c4831d)

I've done some testing on my end with only rough tweaks revamped installed and I've confirmed that it does drop for passive mobs. The ones I tested for now are cows, chickens, sheep, pigs, and horses.

**Comment by SpaceXVI** [comment]
Thank you! Expect an update very soon, will try to add some new content too I guess. Sorry for any inconveniences.

**Comment by DeshiDesu** [comment]
Um... maybe don't announce something you won't do? It's way beyond very soon at this point. I understand you have school, but at the very least, you should have given me an update on your situation. Either way, I'm still cool with it.

**Comment by SpaceXVI** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/rough-tweaks-revamped/files/4747371

Sorry... 😭

**Comment by DeshiDesu** [comment]
haha np
