### ISSUE TITLE
New branch for 1.20

### ISSUE THREAD

**Issue by Stoutscientist** [MostafaSabry55/Rough-Tweaks-Revamped#13]
Hi! I patched it for 1.20 but cannot create a pull request until there's a new branch based on 1.19 for 1.20. I don't think I can create a pull request to add a new branch.

**Comment by SpaceXVI** [comment]
There's already forge 1.20???? I guess I am old now...
Give me a few hours, I have some chemistry to do first haha
Anyway, thank you so much stout you're doing so much for this mod 😭

**Comment by Stoutscientist** [comment]
No problem, I just have too much time lol!

**Comment by Stoutscientist** [comment]
Actually I would like to correct that, it's perfect for procrastinating homework lol

**Comment by zanyahtzee** [comment]
does this mean there's a 1.20 version in the works? im code illiterate and im sorry if thats not the case, im just looking for a rough tweaks port for 1.20.1

**Comment by SpaceXVI** [comment]
I should be getting my school's mid-year break THIS month but I don't know if it'll be enough to even do anything yet (It's just 1 week and either way I'll need to utilize it for studying too..), I guess I'll just leave it up to @Stoutscientist at this point to make the port for now.

Or else we'll have to wait till July where I'll finish 12th grade.

**Comment by SpaceXVI** [comment]
Oh right I will make the branches now too I guess

Edit : Done, 1.19 Branch already exists I just added a 1.20.1, I think this should help if stout or anyone else is down to make an update (Which I'll appreciate very much <3)

**Comment by Stoutscientist** [comment]
> Oh right I will make the branches now too I guess
> 
> Edit : Done, 1.19 Branch already exists I just added a 1.20.1, I think this should help if stout or anyone else is down to make an update (Which I'll appreciate very much <3)

Already done!

**Comment by Stoutscientist** [comment]
> Oh right I will make the branches now too I guess
> 
> Edit : Done, 1.19 Branch already exists I just added a 1.20.1, I think this should help if stout or anyone else is down to make an update (Which I'll appreciate very much <3)

Already done!
