### ISSUE TITLE
I might just be an idiot but there doesn't seem to be a dedicated limb healthbar in the new 1.20.1 port

### ISSUE THREAD

**Issue by zanyahtzee** [MostafaSabry55/Rough-Tweaks-Revamped#15]
Basically the title. I know the mod is active because it shows up in the modlist, as well as the healing items being present and craftable. Natural vanilla minecrarft regeneration seems to also be disabled, however there are no dedicated healthbars for limbs like in older versions. Is that a bug or deliberate? If it's deliberate would it be possible to reintroduce this feature back into the mod?

![2024-01-06_13 42 02](https://github.com/SpaceXVI/Rough-Tweaks-Revamped/assets/104834082/bd7e1884-2c5c-4ff1-bf9b-97694c7638f5)

**Comment by SpaceXVI** [comment]
That's not from my mod, I know the mod you're talking about I just can't remember its name for the life of me!

I'll keep looking around till I find it give me a second.

**Comment by SpaceXVI** [comment]
Is it perhaps this mod? It's called "First Aid"
![screenshot_1](https://github.com/SpaceXVI/Rough-Tweaks-Revamped/assets/64734976/b8f8775e-5df9-4286-81ef-1c02a0ac610e)

There's a 1.19.X version of it, just not a 1.20.X one.

**Comment by zanyahtzee** [comment]
I am in fact an idiot, you're right!

**Comment by SpaceXVI** [comment]
No worries! It's all good, you just didn't know
