### ISSUE TITLE
Natural Health regen is not disabled on new worlds?

### ISSUE THREAD

**Issue by AzureMonument** [MostafaSabry55/Rough-Tweaks-Revamped#4]
I've recently thrown together a modpack for myself, this mod included. However, while deep in the mines on a new world I noticed that I started healing whenever I ate something (natural healing, was eating cave roots courtesy of quark). That's despite the fact I have this mod in and enabled (currently got a couple plasters and bandages in my inventory).

I'm assuming this is probably either a bug in this mod on its own, or a compatibility issue. I'm currently playing on hard mode, and there is no error in the console being detected.  The modpack I threw together is rather large, but I shouldn't (or at least I don't think) I have anything conflicting with this mod in particular (effecting natural health).

Edit: I'm using the latest version, 2.2.2 for 1.16.5
Edit2: I also have health canisters (though I don't think that affects natural regen)

**Comment by SpaceXVI** [comment]
AH crap that's on my side! Will make sure to fix this as soon as possible

**Comment by SpaceXVI** [comment]
Sorry for the wait. This should be fixed in update 2.2.3!
