### ISSUE TITLE
[1.16.5, mod 2.2.3] All items from rough tweaks revamped have zero durability

### ISSUE THREAD

**Issue by Agno1a** [MostafaSabry55/Rough-Tweaks-Revamped#5]
I have tried to reinstall the mod, delete the configs so it generates a new one, but it seems like this won't change.

**Comment by SpaceXVI** [comment]
Holy sh*t, I am fixing that ASAP!

**Comment by SpaceXVI** [comment]
Hmm I am in my test instance and I am not experiencing any issues, I will try building the mod and testing it outside of an IDE

**Comment by Agno1a** [comment]
> Hmm I am in my test instance and I am not experiencing any issues, I will try building the mod and testing it outside of an IDE

What are all the config files related to rough tweaks? I've tried to eliminate the possible problems by erasing the config file, re-downloading the mod and reinstalling it, tried it without using datapacks (I'm using them to change recipes) but the problems stays

**Comment by SpaceXVI** [comment]
If you look at the config you'll find a part called "HealCount", this parts sets all of the item's durabilities.
Also can you please do the following? :
+ This is for your current instance :
 - Send me your current mod list
 - Send me a screenshot of the 0 durability
 - Send me your current config file
 - Send me the steps required to re-create the problem
 - Try obtaining the items through creative mode
+ Make another instance where you :
- Play with only my mod and JEI
- See what's the result

**Comment by SpaceXVI** [comment]
Also I've justed tested the mod myself in an instance with **ONLY** my mod and JEI and it seems to work fine, not sure what's going on here but doing what I listed above would _really_ help

**Comment by Agno1a** [comment]
What version of forge are you using? I created a new instance in multiMC, first I tried to play with Scaling health, rough tweaks, first aid, optifine and jei, then I gradually deleted the other mods, now I only have rough tweaks, jei and optifine and the problems continues
![Uploading 20210225_152830.jpg…]()

**Comment by Agno1a** [comment]
![20210225_152830](https://user-images.githubusercontent.com/79296930/109200057-e5356b00-777e-11eb-846d-3299797037d8.jpg)

**Comment by Agno1a** [comment]
Found out the problem. I used an outdated version of forge and it worked just fine.

**Comment by SpaceXVI** [comment]
So do I mark it as a problem solved?

**Comment by Agno1a** [comment]
Well, I would tell you to keep it open until there is a fix for ir, right? Because other mods seem to work in the most recent versions, and Rough tweaks stops working from forge 36.0.41 up

**Comment by SpaceXVI** [comment]
Wait so it doesn't work with up-to-date forge? I haven't tested it myself

**Comment by Agno1a** [comment]
Yeah, I said I installed an outdated version of forge and only then it worked. I tested many versions, and forge 36.0.41, 36.0.42 and 36.0.43 (released today) do not work with it

**Comment by SpaceXVI** [comment]
Not sure why that would happen, I will try updating forge for rough tweaks then in my IDE, perhaps something changed in forge?

**Comment by Agno1a** [comment]
I really do not understand either. Here's the changelog from forge: 

Build: 1.16.5-36.0.41 - Tue Feb 16 01:28:51 GMT 2021
	knightminer4:
		Fix updateItemStackNBT not properly being called (#7646)
		
		Re-added ItemStack delegate redirect transformer

**Comment by Agno1a** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/7646

**Comment by SpaceXVI** [comment]
That doesn't really relate to the current problem, I will update forge on my IDE and see what happens then

**Comment by SpaceXVI** [comment]
Managed to fix the problem! Bug should be fixed in update 2.2.4!

**Comment by Agno1a** [comment]
> Managed to fix the problem! Bug should be fixed in update 2.2.4!

Good job!
